# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWFlMzM4YjdhY2U1ZTJkNDRjY2Q0OTA5N2UxZmM1YzExZDhiNjA5NGY5ODI5N2U0NGIwODI2ZjU2ZGYyZDQ3NTI0OWE5ZThjYWRkMzI4MDUxZjhhNzMwOTA3YjUyYjEzNzBiOTc1NzcwZDNlYzE2YjJkY2FlMDdlNmJjNTFiODc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
